application: none
version: 1
runtime: python27
api_version: 1
threadsafe: True

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static  # configured in config.py as well
  static_dir: static
- url: /.*
  script: app.handler  # main app handler (uses app.routes to get main routes)
