application: {< application_id >}
version: 1
runtime: python27
api_version: 1
threadsafe: True

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
# configured in config.py as well
- url: /static
  static_dir: static
# main app handler (uses app.routes to get main routes)
- url: /.*
  script: app.handler
